// Auto-detect available i18n locales from `assets/i18n/*.toml` at build time.
// Generates a `LOCALES: &[(&str, &str)]` array — `(locale_code, embedded_toml)`
// — that `src/core/i18n.rs` consumes. Adding / removing a locale is a
// drop-a-file affair; no code changes required.

use std::path::Path;

fn main() {
    let i18n_dir = Path::new("assets/i18n");
    println!("cargo:rerun-if-changed=assets/i18n");

    let mut locales: Vec<String> = Vec::new();
    if let Ok(read) = std::fs::read_dir(i18n_dir) {
        for entry in read.flatten() {
            let path = entry.path();
            if path.extension().and_then(|e| e.to_str()) != Some("toml") {
                continue;
            }
            if let Some(stem) = path.file_stem().and_then(|s| s.to_str()) {
                println!("cargo:rerun-if-changed=assets/i18n/{stem}.toml");
                locales.push(stem.to_string());
            }
        }
    }
    // Stable order: en-US first (the universal fallback), then alphabetical.
    locales.sort_by(|a, b| match (a.as_str(), b.as_str()) {
        ("en-US", "en-US") => std::cmp::Ordering::Equal,
        ("en-US", _) => std::cmp::Ordering::Less,
        (_, "en-US") => std::cmp::Ordering::Greater,
        (x, y) => x.cmp(y),
    });

    // `include_str!` resolves the path relative to the file that contains
    // the macro. The generated `locales.rs` lives in OUT_DIR, so we emit
    // absolute paths to be unambiguous regardless of where the consumer
    // ends up using `include!`.
    let manifest_dir =
        std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR not set by cargo");
    let mut out = String::from(
        "// Auto-generated by build.rs from `assets/i18n/*.toml`. Do not edit.\n\
         pub const LOCALES: &[(&str, &str)] = &[\n",
    );
    for code in &locales {
        let abs = format!("{manifest_dir}/assets/i18n/{code}.toml").replace('\\', "/");
        out.push_str(&format!("    (\"{code}\", include_str!(\"{abs}\")),\n"));
    }
    out.push_str("];\n");

    let out_dir = std::env::var("OUT_DIR").expect("OUT_DIR not set by cargo");
    let out_path = Path::new(&out_dir).join("locales.rs");
    std::fs::write(&out_path, out).expect("write locales.rs");
}
