//! Embedded localisation catalogues and translation lookup.
//!
//! The locale list is generated by `build.rs` from `assets/i18n/*.toml`.
//! Dropping a new `<code>.toml` file there and rebuilding makes it appear
//! in the language picker automatically.

use std::collections::HashMap;
use std::sync::RwLock;

include!(concat!(env!("OUT_DIR"), "/locales.rs"));

// `init(lang)` rewrites both maps, so a language change takes effect on the
// next `t()` call. The fallback is always the first available locale so
// missing keys never crash the UI.
static CATALOG: RwLock<Option<HashMap<String, String>>> = RwLock::new(None);
static FALLBACK: RwLock<Option<HashMap<String, String>>> = RwLock::new(None);
static CURRENT_LANG: RwLock<String> = RwLock::new(String::new());

fn parse(s: &str) -> HashMap<String, String> {
    toml::from_str::<HashMap<String, String>>(s).unwrap_or_default()
}

/// Returns the embedded catalogue text for a locale code, or `None`.
fn lookup_text(code: &str) -> Option<&'static str> {
    LOCALES.iter().find(|(c, _)| *c == code).map(|(_, t)| *t)
}

/// Initialises (or re-initialises) the active catalogue.
///
/// Idempotent and re-entrant; the latest call wins. Unknown or missing
/// locale codes silently fall back to the first available locale.
pub fn init(lang: &str) {
    let active = lookup_text(lang)
        .or_else(|| LOCALES.first().map(|(_, t)| *t))
        .unwrap_or("");
    let fallback = LOCALES.first().map(|(_, t)| *t).unwrap_or("");
    if let Ok(mut g) = CATALOG.write() {
        *g = Some(parse(active));
    }
    if let Ok(mut g) = FALLBACK.write() {
        *g = Some(parse(fallback));
    }
    if let Ok(mut g) = CURRENT_LANG.write() {
        *g = lang.to_string();
    }
}

/// Returns the language code last passed to `init`, or the empty string if
/// `init` has not yet been called.
pub fn current_lang() -> String {
    CURRENT_LANG.read().map(|g| g.clone()).unwrap_or_default()
}

/// Returns every locale the binary was built with as `(code, native_display_name)`.
///
/// The native display name comes from each catalogue's `locale_name` entry
/// and stays in its own language so users can recognise their language
/// regardless of the current UI language.
pub fn available_locales() -> Vec<(String, String)> {
    LOCALES
        .iter()
        .map(|(code, text)| {
            let map = parse(text);
            let native = map
                .get("locale_name")
                .cloned()
                .unwrap_or_else(|| code.to_string());
            (code.to_string(), native)
        })
        .collect()
}

/// Returns the translation for `key`, falling back to the default locale and
/// finally to the key itself when no translation is found.
pub fn t(key: &str) -> String {
    if let Ok(g) = CATALOG.read() {
        if let Some(map) = g.as_ref() {
            if let Some(v) = map.get(key) {
                return v.clone();
            }
        }
    }
    if let Ok(g) = FALLBACK.read() {
        if let Some(map) = g.as_ref() {
            if let Some(v) = map.get(key) {
                return v.clone();
            }
        }
    }
    key.to_string()
}

/// Returns the translation for `key` with `{name}` placeholders substituted
/// from `args`.
pub fn t_args(key: &str, args: &[(&str, &str)]) -> String {
    let mut s = t(key);
    for (k, v) in args {
        s = s.replace(&format!("{{{k}}}"), v);
    }
    s
}
